version: 3
# This section below comes from a separate config file that isn't committed
# agent:
#   authtoken: HIDDEN
endpoints:
  - name: surefin_local_carson
    url: https://shown-engaging-tackiness.ngrok-free.dev
    upstream:
      url: 3333
