version: 3
# This section below comes from a separate config file that isn't committed
# agent:
#   authtoken: HIDDEN

endpoints:
  - name: proxy_gateway
    upstream:
      url: http://localhost:8080
    # traffic_policy:
    #   on_http_request:
    #     # Prompt for username and password
    #     - actions:
    #         - type: basic-auth
    #           config:
    #             credentials:
    #               - carson:password
